TARGET = "STM32F407_EJD"

PLATFORM_BUILD_PATH = ${PLATFORM_PATH}/out
PLATFORM_TARGET_PLAT_DIR = ${PLATFORM_PATH}/makerules
PLATFORM_TARGET_RELEASE_DIRECTORY  = ${PLATFORM_PATH}/release
# EXEC_PATH = ${PLATFORM_PATH}/platform_release/toolchain/gcc-arm-none-eabi-8-2018-q4-major/bin
EXEC_PATH = ${PLATFORM_PATH}/platform_release/toolchain/gcc-arm-none-eabi-6_2-2016q4/bin

export PLATFORM_BUILD_PATH PLATFORM_TARGET_PLAT_DIR PLATFORM_TARGET_RELEASE_DIRECTORY
export TARGET EXEC_PATH

